query getCurrentEvent {
    getCurrentEvent {
        id
        eventType {
            id
            name
            description
        }
        year
        startDate
        donations
        donors
        completedGames
        tweets
        twitchChats
        viewers
        scheduleId
    }
    getGames {
        name
        runners
        startDate
        endDate
        duration
    }
    getAlternativeEvents {
        id
        year
        eventType {
            name
        }
    }
}
