query getCurrentEvent {
  getCurrentEvent {
    id
    eventType {
      id
      name
      description
    }
    year
    start_date
    donations
    donors
    games_completed
    tweets
    twitch_chats
    viewers
    scheduleId
  }
  getGames {
    name
    runners
    start_date
    end_date
    duration
  }
  getAlternativeEvents {
    id
    year
    eventType {
      name
    }
  }
}
