query getAdminData {
    getEventTypes @list(name: "All_Event_Types") {
        id
        name
        description
    }
    getEvents @list(name: "All_Events") {
        id
        eventType {
            name
        }
        activeEvent
        donations
        donors
        completedGames
        totalGames
        tweets
        twitchChats
        viewers
        year
        eventDataCount
        scheduleId
    }
}
